version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - prod.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server_alpha_db.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$DB_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # It's possible to specify the image to use in the environment, default is the latest image from the github container registry
    image: "${SERVER_IMAGE:-ghcr.io/wwi21seb-projekt/server-alpha:main}"
    depends_on:
      - db
    env_file:
      - prod.env
    environment:
      - LOCAL_DB_HOST=db
      - LOCAL_DB_PORT=${DB_PORT}
      - LOCAL_DB_NAME=${DB_NAME}
      - LOCAL_DB_USER=${DB_USER}
      - LOCAL_DB_PASSWORD=${DB_PASS}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}

volumes:
  db_data: