name: Continuous Delivery

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./build/package/Dockerfile

      - name: Copy docker-compose prod file to server
        env:
          SERVER_IMAGE: ghcr.io/wwi21seb-projekt/server-alpha:main
          TRAFFIC_RULE: Host(`server-alpha.tech`)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "deployments/docker-compose.prod.yml,deployments/server_alpha_db.sql"
          target: "/home/serveralpha"

      - name: Setup SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |          
            echo "SERVER_IMAGE=${SERVER_IMAGE}" >> .env
            echo "TRAFFIC_RULE=${TRAFFIC_RULE}" >> .env
            
            docker pull ${{ steps.meta.outputs.tags }}
            docker-compose -f deployments/docker-compose.prod.yml -p server_alpha down
            docker-compose -f deployments/docker-compose.prod.yml -p server_alpha up -d
