name: Continuous Delivery
run-name: Deploy to Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-push-docker:
    uses: ./.github/workflows/build-push-image.yaml
    with:
      preview: false
      secrets: inherit

  deploy:
    needs: build-push-docker
    uses: ./.github/workflows/pr-cleanup.yaml
    with:
      preview: false
      docker-image: ${{ steps.meta.outputs.tags }}
      compose-name: "server_alpha"
      ssh-script: |
        set_key_value "SERVER_IMAGE" "ghcr.io/wwi21seb-projekt/server-alpha:main" ".env"
        set_key_value "TRAFFIC_RULE" "Host(\`server-alpha.tech\`)" ".env"
        set_key_value "MONITORING_TRAFFIC_RULE" "Host(\`monitoring.server-alpha.tech\`)" ".env"
    secrets: inherit
