name: PR Cleanup
run-name: Cleanup PR-${{ github.event.pull_request.number }} Preview

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]' # Don't run this workflow for renovate bot

    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ./preview/pr-${{ github.event.pull_request.number }}
            docker-compose -f deployments/docker-compose.prod.yml -p pr_${{ github.event.pull_request.number }} down || true
            docker-compose -f deployments/docker-compose.prod.yml -p pr_${{ github.event.pull_request.number }} down -v || true
            docker image rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }} || true                          
            rm -rf ~/preview/pr-${{ github.event.pull_request.number }}
